### ISSUE TITLE
Checboxes need a text

### ISSUE THREAD

**Issue by hrshahriari** [mohamadch91/inventory-front-end#12]
کنار صفحاتی که جواب آنها Yes/no است و انتخاب به معنی Yes است کلمه Yes کنار چک باکس نوشته شود. یا که radio button شود: yes  ,   no

![image](https://user-images.githubusercontent.com/50543828/187084831-37d5bbf9-2430-4c10-8229-c7a84593539a.png)

**Comment by mohamadch91** [comment]
done
