### ISSUE TITLE
"New Facilities" and "New Item" tabs movement

### ISSUE THREAD

**Issue by hrshahriari** [mohamadch91/inventory-front-end#15]
برای جابجایی بین تب ها در New facilities و جاهای مشابه دیگر، دو دکمخ Next و Back بالا آورده شده.
- اول اینکه این دو متن ساده هستند. باید دکمه مشخص و بهتر اینکه فلش به چپ و راست باشند.
- پایین صفحه هم این دکمه ها بیایند. 
- الان کاربر در پایین تب سردرگم می شود. یه جوری باید بفهمد که باید Next را بزند و فعلا نیازی به Save نیست.

**Comment by mohamadch91** [comment]
done
