### ISSUE TITLE
Item list --> Edit item

### ISSUE THREAD

**Issue by hrshahriari** [mohamadch91/inventory-front-end#18]
وقتی در Item list روی Edit میزنیم، کلا دیگه چیزی نشون نمیده!
(با دو مرورگر فایرفاکس و اپرا امتحان شده هر دو کار نکرد!)
مگه این که رفرش کنیم!

![image](https://user-images.githubusercontent.com/50543828/188271102-a9850036-cd95-44d5-bcdf-6191dea7d7a1.png)

![image](https://user-images.githubusercontent.com/50543828/188271171-08f467d6-431e-4df9-a968-b08496313c01.png)

![image](https://user-images.githubusercontent.com/50543828/188271146-4040eab3-b2c4-41fc-9370-4a1402f953a1.png)

**Comment by mohamadch91** [comment]
debug completed
