### ISSUE TITLE
Print Item Form is empty

### ISSUE THREAD

**Issue by hrshahriari** [mohamadch91/inventory-front-end#19]
Print Item Form is empty.
این فرمهای خالی کاربردش فقط اینه پرینت کنند که بدن دست کاربر بره دستی پر کنه! بعدا یکی دیگه بیاد از
 روی فرم وارد سیستم کنه.
نمونه فرم از خود سایت آذربایجان

[Uploading New Items form.pdf…]()

**Comment by mohamadch91** [comment]
done
